"""adding image field

Revision ID: f59db417ebb3
Revises: c6a8536a2506
Create Date: 2021-01-14 19:45:23.624375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f59db417ebb3'
down_revision = 'c6a8536a2506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'url')
    # ### end Alembic commands ###
